set(_CATKIN_CURRENT_PACKAGE "rt_detect")
set(rt_detect_VERSION "0.1.0")
set(rt_detect_MAINTAINER "MMG <782470390@qq.com>")
set(rt_detect_PACKAGE_FORMAT "2")
set(rt_detect_BUILD_DEPENDS "roscpp" "sensor_msgs" "cv_bridge" "autoware_msgs")
set(rt_detect_BUILD_EXPORT_DEPENDS )
set(rt_detect_BUILDTOOL_DEPENDS "catkin")
set(rt_detect_BUILDTOOL_EXPORT_DEPENDS )
set(rt_detect_EXEC_DEPENDS "roscpp" "sensor_msgs" "cv_bridge" "autoware_msgs")
set(rt_detect_RUN_DEPENDS "roscpp" "sensor_msgs" "cv_bridge" "autoware_msgs")
set(rt_detect_TEST_DEPENDS )
set(rt_detect_DOC_DEPENDS )
set(rt_detect_URL_WEBSITE "")
set(rt_detect_URL_BUGTRACKER "")
set(rt_detect_URL_REPOSITORY "")
set(rt_detect_DEPRECATED "")